version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xiam_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  xiam:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/xiam_prod"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-PleaseGenerateAProperSecretInProduction}"
      PHX_HOST: "${PHX_HOST:-localhost}"
      PORT: 4000
      POOL_SIZE: 10
      RELEASE_COOKIE: "xiam_cookie"
      JWT_SECRET: "${JWT_SECRET:-ChangeThisToSecureRandomStringInProduction}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-changeme123}"
    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  postgres_data:
